from rest_framework import serializers
from .models import UserProfile , BlogPostRequest
from django.contrib.auth.models import User

class UserProfileSerializer(serializers.ModelSerializer):
    class Meta:
        model = UserProfile
        fields = ['profile_picture']


class UserSerializer(serializers.ModelSerializer):
    profile = UserProfileSerializer()  # Nested serializer for profile data

    class Meta:
        model = User
        fields = ['id', 'username', 'first_name', 'last_name', 'email', 'profile']
        
class BlogPostRequestSerializer(serializers.ModelSerializer):
    class Meta:
        model = BlogPostRequest
        fields = ['topic', 'tone', 'length', 'content_method', 'content']
        read_only_fields = ['content']  # Content will be generated by AI and not provided by the user
