# Generated by Django 5.1.4 on 2024-12-19 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpostrequest',
            name='tone',
            field=models.CharField(choices=[('neutral', 'Neutral'), ('informal', 'Informal'), ('friendly', 'Friendly'), ('professional', 'Professional')], default='friendly', max_length=50),
        ),
    ]
